name: tests

on: 
  push
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git libtool tmux python3-pip
          sudo pip3 install flask pytest pytest-dependency requests

      - name: Run tests 
        run: pytest -s app/tests/ --coverage
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v1
